### ISSUE TITLE
Is it possible to change RxSwift dependency to 2.2.0 ?

### ISSUE THREAD

**Issue by HAKASHUN** [SideEffects-xyz/RxBluetooth#4]
Yesterday [RxSwift 2.2.0](https://github.com/ReactiveX/RxSwift/releases/tag/2.2.0) was released.
Is it possible to change RxSwift dependency to 2.2.0 ?

**Comment by mane87** [comment]
I will have a look at it on the weekend.

**Comment by HAKASHUN** [comment]
:+1:

**Comment by bontoJR** [comment]
Done, thanks!
