### ISSUE TITLE
Default Branch

### ISSUE THREAD

**Issue by ashfurrow** [SideEffects-xyz/RxBluetooth#6]
From the readme:

> Contributions are welcomed in the develop repository. Any pull-request to the master branch will be rejected.

Under the repo settings, you can set the "Default branch" to be `develop`, which will be checked out by default and all new PRs will be default be submitted against. Definitely work considering.

**Comment by bontoJR** [comment]
Thanks @ashfurrow. Totally forgot about that, I also disabled force-pushes on the master branch :+1:

**Comment by ashfurrow** [comment]
Cool!
